CREATE TABLE IF NOT EXISTS goTodo(
  id SERIAL PRIMARY KEY,
  title varchar(255) NOT NULL,
  completed BOOLEAN DEFAULT FALSE,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
);